# Generated by Django 2.2.2 on 2019-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_maincarousel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to='static/bg_images')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BG Image',
                'verbose_name_plural': 'Background Images',
            },
        ),
    ]
