# Generated by Django 2.2.2 on 2019-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
