# Generated by Django 2.2.2 on 2019-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20190727_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincarousel',
            name='image',
            field=models.ImageField(upload_to='static/img_carousel'),
        ),
    ]
