# Generated by Django 2.2.2 on 2019-06-29 16:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190629_1806'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productimage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
