# Generated by Django 2.2.2 on 2019-06-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='final_price',
        ),
    ]
