# Generated by Django 2.2.2 on 2019-07-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190706_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
