# Generated by Django 2.2.2 on 2019-06-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190622_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product in Order', 'verbose_name_plural': 'Products in Order'},
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='nmb',
            new_name='quantity',
        ),
    ]
