# Generated by Django 2.2.2 on 2019-06-25 18:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190623_1839'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productinorder',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
