# Generated by Django 2.2.2 on 2019-07-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190704_2158'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productincart',
            managers=[
            ],
        ),
    ]
