# Generated by Django 2.2.2 on 2019-07-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190704_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='price',
            new_name='final_price',
        ),
    ]
