# Generated by Django 2.2.2 on 2019-07-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190706_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='quantity',
            new_name='nmb',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='productincart',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
