# Generated by Django 2.2.2 on 2019-07-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190706_1220'),
        ('orders', '0018_auto_20190706_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='quantity',
            new_name='nmb',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='quantity',
            new_name='nmb',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='product',
        ),
        migrations.AddField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product'),
        ),
    ]
