# Generated by Django 2.2.2 on 2019-07-08 17:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productincart',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
