# Generated by Django 2.2.2 on 2019-07-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_productincart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='image',
        ),
    ]
