# Generated by Django 2.2.2 on 2019-07-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_productinorder_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='image_path',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
