# Generated by Django 2.2.2 on 2019-07-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190704_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='product',
        ),
        migrations.AddField(
            model_name='productincart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
