# Generated by Django 2.2.2 on 2019-07-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190706_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productincart',
            old_name='nmb',
            new_name='quantity',
        ),
    ]
