# Generated by Django 2.2.2 on 2019-07-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190704_2210'),
        ('orders', '0017_auto_20190706_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='product',
        ),
        migrations.AddField(
            model_name='productincart',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
