# Generated by Django 2.2.2 on 2019-07-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190708_2004'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productincart',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productinorder',
            managers=[
            ],
        ),
    ]
