# Generated by Django 2.2.2 on 2019-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_productincart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='image_path',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
