# Generated by Django 2.2.2 on 2019-07-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20190727_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='image_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
