# Generated by Django 2.2.2 on 2019-06-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190626_2321'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productimage',
            managers=[
            ],
        ),
    ]
