# Generated by Django 2.2.2 on 2019-07-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190704_2210'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='productimage',
            managers=[
            ],
        ),
    ]
