# Generated by Django 2.2.2 on 2019-07-06 12:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190706_1220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productimage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True),
        ),
    ]
