# Generated by Django 2.2.2 on 2019-07-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190719_1941'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productimage',
            managers=[
            ],
        ),
    ]
